name: Hello World
on:
  push:
    branches: [ "main" ]
jobs:
  jhc_build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Java Home Workshop
        run: echo "Welcome to Github Actions"
