name: Docker CI/CD - Java Home
on:
  push:
    branches: [ "main" ]
jobs:
  dokcer_build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Get latest commit hash
        id: commit
        run: echo "::set-output name=hash::$(git rev-parse --short HEAD)"
        
      - name: Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: kammana/wsapp:${{ steps.commit.outputs.hash }}

      - name: Run Docker container on remote host
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_DOCKER_HOST }}
          username: ${{ secrets.DEV_DOCKER_USER }}
          key: ${{ secrets.DEV_DOCKER_KEY }}
          script: |
            docker rm -f wsapp 2> /dev/null || true
            docker pull kammana/wsapp:${{ steps.commit.outputs.hash }}
            docker run -d --name wsapp -p 8080:8080 kammana/wsapp:${{ steps.commit.outputs.hash }}
